### PR TITLE
fix caption classifier dying on empty table rows

### PR DESCRIPTION
**Pull request by axfelix**
Hi Martin,

This fixes this document dying:

[6721-85-15443-1-11-20170717.docx](https://github.com/MartinPaulEve/meTypeset/files/2116233/6721-85-15443-1-11-20170717.docx)

Let me know if you'd like a minimal test case for this too.

### CODE REVIEW

**Comment by MartinPaulEve** [comment]
If there is a minimal doc and test case for this yes please - it's the only
way we can avoid regressions.

**Comment by axfelix** [comment]
[EmptyRows.docx](https://github.com/MartinPaulEve/meTypeset/files/2117123/EmptyRows.docx)

K, minimal doc successfully created, just have to remind myself how to make a test for it

**Comment by axfelix** [comment]
Should do it!

**Comment by MartinPaulEve** [comment]
This pull seems to still have a failing test.

Inside the document we have:

`<table-wrap specific-use="rules" position="float" orientation="portrait">
        <table>
          <tr>Article</tr>
        </table>
      </table-wrap>`

But think it's looking for Element Should Exist    ${xml}    table/tr

Changing to body//table/tr should do it. Fixing and committing if all other tests pass.

**Pull request merged**
