### PR TITLE
consolidate the working @sebastianmng fixes

### PR DESCRIPTION
**Pull request by axfelix**
This collects all of the minor improvements made by @sebastianmng to fix edge case crashes and mis-tagging with the exception of the major change to running the bibliography parser before the list classifier; that one might be revisited at a later date. All tests are passing.

### CODE REVIEW

**Comment by axfelix** [comment]
Hi @MartinPaulEve, preparing the updated tests, just wanted to let you know I'll probably not be adding a test case for this fix as it was clearly a typo in the original code: https://github.com/sebastianmng/meTypeset/commit/ab93e3ed5f9a50e40dfad6583429b7dd40128463

**Comment by axfelix** [comment]
Should be ready to merge now!

**Comment by MartinPaulEve** [comment]
Hi Alex,

These commits seem to break tests 024 and 034... Is that not the case on your system?

Best wishes,

Martin

**Comment by axfelix** [comment]
Shoot. I was sure I'd run all the tests on this branch in between committing the changes a month ago and actually writing the new tests last week, but obviously my memory was faulty. Will revisit.

**Comment by axfelix** [comment]
Ahem. passing now. Thank you for catching that; in my defense the source material I was working from was a little messy...

**Comment by MartinPaulEve** [comment]
Thanks, @axfelix! All merged!

**Pull request merged**
