### PR TITLE
BUG FIX for python2 support

### PR DESCRIPTION
**Pull request by withanage**

### CODE REVIEW

**Comment by withanage** [comment]
Hi Martin,
sorry, i could not clarify the issue, I found that  metypeset was producing an error for  several files for python2 , although it workd fine for python3.


```bash
Traceback (most recent call last):
  File "/home/wit/projects/meTypeset/bin/meTypeset.py", line 256, in <module>
    main()
  File "/home/wit/projects/meTypeset/bin/meTypeset.py", line 252, in main
    me_typeset_instance.run()
  File "/home/wit/projects/meTypeset/bin/meTypeset.py", line 244, in run
    self.run_modules()
  File "/home/wit/projects/meTypeset/bin/meTypeset.py", line 231, in run_modules
    manipulate.final_clean()
  File "/home/wit/projects/meTypeset/bin/nlmmanipulate.py", line 505, in final_clean
    self.handle_stranded_reference_titles_from_cues()
  File "/home/wit/projects/meTypeset/bin/nlmmanipulate.py", line 550, in handle_stranded_reference_titles_from_cues
    with open ('{0}/language/ref_marker_{1}.txt'.format(self.gv.script_dir, language), 'r', encoding="utf8") as lang_file:
TypeError: 'encoding' is an invalid keyword argument for this function

```

**Comment by MartinPaulEve** [comment]
@axfelix - could you have a look at this and check it doesn't conflict with
your python3 patch?

Dulip - we're moving to require python3 at the moment...

**Comment by axfelix** [comment]
This is far from the only non backwards compatible change, I'm not sure I'd merge this on its own -- if you really want to add if logic for all the changed code paths, I'd take a look at all the recent Python 3 commits...

**Comment by MartinPaulEve** [comment]
@withanage - is there a reason why your environment can't run python3? We'd like to drop support for python2.

**Comment by withanage** [comment]
@MartinPaulEve 

There wasn't a special reason , only the interactive modus for python3 failed in this case, and I did not have the time to look into it, although it  is a minor issue, which can be fixed easily.

```bash
python3 bin/meTypeset.py docx tests/ReferenceWithTrailingAcknowledgement.docx --interactive  ReferenceWithTrailingAcknowledgement

```
```python
sel = prompt.input_options(opts)
  File "/home/wit/projects/meTypeset/bin/interactive.py", line 93, in input_options
    (isinstance(default, basestring) and
NameError: name 'basestring' is not defined
```
I will also go for python3  and update the server systems accordingly and therefore python2 support  is also needed by my side.

Therefore I will close the pull request

**Pull request closed without merging**
